version: 2.1
jobs:
    build:
        branches:
            only:
                - develop
        working_directory: ~/public
        docker:
            - image: circleci/node:10.15.3
        steps:
            - checkout
            - run:
                  name: update-npm
                  command: 'sudo npm install -g npm@latest'
            - restore_cache:
                  key: dependency-cache-{{ checksum "package.json" }}
            - run:
                  name: install-npm-wee
                  command: npm install
            - save_cache:
                  key: dependency-cache-{{ checksum "package.json" }}
                  paths:
                      - ./node_modules
            - run:
                  name: test
                  command: npm test
            - store_artifacts:
                  path: test-results.xml
                  prefix: tests
            - store_artifacts:
                  path: coverage
                  prefix: coverage
            - store_test_results:
                  path: test-results.xml

    deploy:
        docker:
            - image: buildpack-deps:trusty
        steps:
            - checkout
            - run:
                  name: Deploy Master to Heroku
                  command: |
                      git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
    version: 2.1
    build-deploy:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
                  filters:
                      branches:
                          only: develop
